server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;  
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?s=$uri&$args;  # 如果文件不存在则交给 index.php
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;  # 这里的 'php' 是 PHP-FPM 容器的服务名，确保和 Docker Compose 中的服务名称一致
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

    }

    # 其他静态文件处理
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}